### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by certik** [xonsh/minixonsh#4]
After #3 is merged, we need to add a CI. @scopatz what CI should I setup for Linux, macOS and Windows? Perhaps I can do Azure pipelines, that have all three platforms.

**Comment by melund** [comment]
GitHub actions also works fine. It is a little similar to Azure pipelines but a little simpler.

**Comment by certik** [comment]
@melund I need to learn how to use the GitHub actions, I haven't used them yet.

**Comment by scopatz** [comment]
I am open to any CI that works :wink:

**Comment by certik** [comment]
I've added GitHub actions in #5, #7. So far only on Linux. I created #9 for macOS and Windows support.

**Comment by certik** [comment]
Minixonsh now runs on Windows and macOS and tests pass.
